services:
  api:
    container_name: api-nest
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    entrypoint: wait-for postgres:5432 -t 40 -- ./start-api.sh
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    container_name: api-postgres
    image: postgres:latest
    volumes:
      - ./.volumes/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
  observability:
    driver: "bridge"
